- name: Container is running
  docker:
    image: google/cadvisor
    name: cadvisor
    privileged: yes
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro 
    ports:
      - 8081:8080
  tags: [cadvisor]

